import { StyleSheet } from 'react-native';
import { colors, spacing } from '@beeapp/design-system';

const BEE_PURPLE = '#7427D5';
const BEE_PURPLE_DARK = '#5E1ABF';
const BEE_PURPLE_LIGHT = '#F6EAFE';
const BEE_PURPLE_BORDER = '#E8D1F1';
const BEE_TEXT = '#261743';

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FFFCF9',
    },
    container: {
        flex: 1,
        backgroundColor: '#FFFCF9',
    },
    content: {
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 36,
    },

    header: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        marginBottom: 24,
    },
    headerTextColumn: {
        flex: 1,
        paddingRight: 12,
    },
    headerTitle: {
        fontSize: 24,
        lineHeight: 30,
        fontWeight: '800',
        color: BEE_PURPLE,
    },
    headerSubtitle: {
        marginTop: 2,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: '400',
        color: '#7865AD',
    },
    avatar: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: '#E6C7EE',
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#6F409B',
    },

    aiSearchCard: {
        minHeight: 174,
        overflow: 'hidden',
        borderRadius: 22,
        backgroundColor: BEE_PURPLE,
        paddingHorizontal: 20,
        paddingTop: 22,
        paddingBottom: 20,
        marginBottom: 26,
        shadowColor: BEE_PURPLE_DARK,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.24,
        shadowRadius: 14,
        elevation: 5,
    },
    aiGlowLarge: {
        position: 'absolute',
        width: 190,
        height: 190,
        borderRadius: 95,
        right: -78,
        top: 18,
        backgroundColor: 'rgba(173, 92, 255, 0.28)',
    },
    aiGlowSmall: {
        position: 'absolute',
        width: 115,
        height: 115,
        borderRadius: 58,
        right: -12,
        top: 36,
        backgroundColor: 'rgba(202, 137, 255, 0.16)',
    },
    aiSearchTitle: {
        fontSize: 18,
        lineHeight: 23,
        fontWeight: '800',
        color: colors.neutral.white,
    },
    aiSearchDescription: {
        maxWidth: '84%',
        marginTop: 4,
        fontSize: 13,
        lineHeight: 19,
        fontWeight: '400',
        color: 'rgba(255,255,255,0.94)',
    },
    searchInputMock: {
        minHeight: 48,
        marginTop: 16,
        paddingLeft: 14,
        paddingRight: 7,
        borderRadius: 24,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.neutral.white,
    },
    sparkleIconWrap: {
        width: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchInputText: {
        flex: 1,
        marginLeft: 5,
        marginRight: 8,
        fontSize: 12,
        lineHeight: 17,
        fontWeight: '400',
        color: '#695E78',
    },
    voiceButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: BEE_PURPLE,
        alignItems: 'center',
        justifyContent: 'center',
    },

    businessCard: {
        minHeight: 110,
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: BEE_PURPLE_BORDER,
        backgroundColor: BEE_PURPLE_LIGHT,
        paddingHorizontal: 20,
        paddingVertical: 16,
        marginBottom: 27,
    },
    businessIconWrap: {
        width: 52,
        height: 52,
        borderRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.neutral.white,
        shadowColor: '#A788B2',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.08,
        shadowRadius: 7,
        elevation: 2,
    },
    businessTextColumn: {
        flex: 1,
        marginLeft: 15,
        marginRight: 10,
    },
    businessTitle: {
        fontSize: 15,
        lineHeight: 20,
        fontWeight: '700',
        color: BEE_TEXT,
    },
    businessDescription: {
        marginTop: 3,
        fontSize: 12,
        lineHeight: 17,
        fontWeight: '400',
        color: '#8A68B5',
    },
    businessArrowButton: {
        width: 36,
        height: 36,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: BEE_PURPLE,
    },

    section: {
        marginBottom: 27,
    },
    sectionTitle: {
        marginBottom: 13,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: '700',
        color: BEE_TEXT,
    },

    quickActionsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    quickActionCard: {
        width: '31.3%',
        minHeight: 82,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#EEE8F1',
        backgroundColor: colors.neutral.white,
        shadowColor: '#2A1A45',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 1,
    },
    quickActionIconWrap: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: BEE_PURPLE_LIGHT,
        marginBottom: 7,
    },
    quickActionLabel: {
        fontSize: 11,
        lineHeight: 14,
        fontWeight: '500',
        color: '#38294E',
        textAlign: 'center',
    },

    categoryGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        rowGap: 14,
    },
    categoryCard: {
        width: '48%',
        minHeight: 138,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: '#F0EAF3',
        backgroundColor: colors.neutral.white,
        paddingHorizontal: 18,
        paddingTop: 19,
        paddingBottom: 16,
        shadowColor: '#2A1A45',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.07,
        shadowRadius: 9,
        elevation: 2,
    },
    categoryIconWrap: {
        width: 39,
        height: 39,
        borderRadius: 13,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: BEE_PURPLE_LIGHT,
        marginBottom: 12,
    },
    categoryTitle: {
        fontSize: 15,
        lineHeight: 20,
        fontWeight: '700',
        color: '#2D2141',
    },
    categorySubtitle: {
        marginTop: 3,
        fontSize: 11,
        lineHeight: 15,
        fontWeight: '400',
        color: '#8A72B2',
    },

    footer: {
        alignItems: 'center',
        paddingTop: 18,
        paddingBottom: spacing.sm,
    },
    footerText: {
        fontSize: 10,
        lineHeight: 14,
        fontWeight: '400',
        color: '#594C67',
    },
    footerLine: {
        width: 34,
        height: 3,
        borderRadius: 2,
        marginTop: 6,
        backgroundColor: '#D8AEE5',
    },
});